defaults:
  - task: ???
  - algo: ppo
  - _self_

headless: true
seed: 42
num_envs: 4096

checkpoint: null    # path to checkpoint for resuming training

log_root: /scratch2/danielc174/humanoid-rl/outputs

wandb:
  project: humanoid-rl
  mode: disabled
  notes: ""

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false